# Generated by Django 3.1.4 on 2021-01-06 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('character', models.TextField()),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CrawledDogs',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('dogid', models.IntegerField(default=0)),
                ('detailedurl', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dogsphotos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=50)),
                ('num', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PostedDogs',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('protection', models.CharField(max_length=50)),
                ('dogid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doglist.characters')),
            ],
        ),
        migrations.CreateModel(
            name='PostedInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dogs',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='doglist.posteddogs')),
                ('name', models.CharField(max_length=50)),
                ('dogtype', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('uniqueness', models.CharField(max_length=50)),
                ('photoid', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('idname', models.CharField(max_length=50)),
                ('pw', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('phonenum', models.IntegerField(default=0)),
                ('address', models.TextField()),
                ('photourl', models.TextField()),
                ('characterid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doglist.characters')),
            ],
        ),
        migrations.AddField(
            model_name='posteddogs',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doglist.users'),
        ),
    ]
