# Generated by Django 3.1.6 on 2021-03-29 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UHG', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogs',
            name='uniqueness',
            field=models.CharField(max_length=500),
        ),
    ]
