# Generated by Django 3.1.6 on 2021-03-30 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UHG', '0003_auto_20210329_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='characters',
            name='originType',
            field=models.TextField(default=''),
        ),
    ]
